production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRESQL_DATABASE']%>
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME']%>
  password: <%= ENV['POSTGRESQL_PASSWORD']%>
  host: <%= ENV['POSTGRESQL_ADDRESS']%>
  port: 5432
